services:
  backend:
    build: ./backend
    container_name: crop-backend
    ports:
      - "8010:8000"
    restart: unless-stopped

  frontend:
    build: ./frontend/cropmanager-frontend
    container_name: crop-frontend
    ports:
      - "3010:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=0\
      - REACT_APP_API_BASE=http://backend:8000
    depends_on:
      - backend
    restart: unless-stopped
